[package]
name = "varutil"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1"
serde = { version = "1",  features = ["derive"] }
serde_json = "1"
